services:
  - type: web
    name: twitter-sentiment-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run src/dashboard.py --server.port=$PORT --server.address=0.0.0.0
"